[package]
name = "serde_cbor"
version = "0.9.0"
authors = [
    "Pyfisch <pyfisch@gmail.com>",
    "Steven Fackler <sfackler@gmail.com>"]
repository = "https://github.com/pyfisch/cbor"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "CBOR support for serde."
keywords = ["serde", "cbor", "serialization"]
categories = ["encoding"]
edition = "2018"

[badges]
travis-ci = { repository = "pyfisch/cbor" }
maintenance = { status = "actively-developed" }

[dependencies]
byteorder = "1.0.0"
half = "1.2.0"
serde = "1.0.14"

[dev-dependencies]
serde_bytes = "0.10"
serde_derive = "1.0.14"
