[package]
name = "serde_cbor"
version = "0.5.0"
authors = ["Pyfisch <pyfisch@gmail.com>"]
repository = "https://github.com/pyfisch/cbor"
documentation = "http://pyfisch.github.io/cbor/serde_cbor/index.html"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "CBOR serialization and deserialization using serde."
keywords = ["serde", "cbor", "serialization"]

[dependencies]
byteorder = "1.0"
serde = "0.9.0"
serde_derive = { version="0.9.0", optional=true }

[features]
unstable = ["serde_derive"]
